---
# SPDX-FileCopyrightText: 2024 Cognitive Disorders Research Lab
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
openapi: 3.1.0
info:
    title: Gene Information API
    version: 1.0.0
    description: A read-only API that provides information about genes from various sources.
servers:
    - url: https://kaleidoscope.cdrlprojects.org/v1
security:
    - bearerAuth: []
paths:
    /gtex:
        post:
        summary: Get GTEx information for multiple genes at once
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
        responses:
            200:
                description: Successful response
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/GtexResponse'
            400:
                description: Invalid gene name
            500:
                description: Internal server error
    /gtex/{geneName}:
        get:
            summary: Get GTEx information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GtexResponse'
                404:
                    description: Gene not found
                400:
                    description: Invalid gene name
                500:
                    description: Internal server error
    # TODO: STRING needs redoing
    /string/{geneName}:
        get:
            summary: Get STRING information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StringResponse'
                '404':
                    description: Gene not found
    /ilincs/{geneName}:
        get:
            summary: Get ILINCS information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IlincsSummaryResponse'
                404:
                    description: Gene not found
                400:
                    description: Invalid gene name
                500:
                    description: Internal server error
    /ilincs/{geneName}/signatures:
        get:
            summary: Get ILINCS perturbation signatures for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IlincsSignatureResponse'
                404:
                    description: Gene not found
                400:
                    description: Invalid gene name
                500:
                    description: Internal server error
    /braincloud/{geneName}:
        get:
            summary: Get Braincloud information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BraincloudResponse'
                '404':
                    description: Gene not found
    /brainrnaseq:
        post:
            summary: Get Brain-RNASeq information for multiple genes at once
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/BrainRnaseqResponse'
                400:
                    description: Invalid gene name
                404:
                    description: Gene not found
                500:
                    description: Internal server error
    /brainrnaseq/{geneName}:
        get:
            summary: Get Brain-RNASeq information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BrainRnaseqData'
                404:
                    description: Gene not found
                400:
                    description: Invalid gene name
                500:
                    description: Internal server error
    /brainatlas/{geneName}:
        get:
            summary: Get BrainAtlas information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BrainatlasResponse'
                '404':
                    description: Gene not found
    /idg/{geneName}:
        get:
            summary: Get IDG information for a gene
            parameters:
                - name: geneName
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IdgResponse'
                404:
                    description: Gene not found
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        GtexTissueData:
            type: object
            properties:
                tissueType:
                    type: string
                tissueExpression:
                    type: float
        GtexResponse:
            type: object
            properties:
                geneName:
                    type: string
                expressionData:
                    type: array
                    items:
                    $ref: '#/components/schemas/GtexTissueData'
        StringResponse:
            type: object
            properties:
                geneName:
                    type: string
                proteinInteractions:
                    type: array
                    items:
                        type: object
        IlincsSummaryData:
            type: object
            properties:
                num_overexpression:
                    type: integer
                num_knockdown:
                    type: integer
        IlincsSummaryResponse:
            type: object
            properties:
                geneName:
                    type: string
                summaryData:
                    $ref: '#/components/schemas/IlincsSummaryData'
        IlincsSignatureData:
            type: object
            properties:
                signature_id:
                    type: string
                gene_perturbed:
                    type: string
                cell_line:
                    type: string
                tissue_type:
                    type: string
                perturbation_type:
                    type: enum
                    enum:
                        - overexpression
                        - knockdown
        IlincsSignatureResponse:
            type: array
            items:
                $ref: '#/components/schemas/IlincsSignatureData'
        BrainCloudResponse:
            type: object
            properties:
                geneName:
                    type: string
                brainExpression:
                    type: object
        BrainRNASeqData:
            type: object
            properties:
                gene_name:
                    type: string
                species:
                    type: enum
                    enum:
                        - human
                        - mouse
                cell_type:
                    type: string
                expression:
                    type: float
        BrainRNASeqResponse:
            type: array
            items:
                $ref: '#/components/schemas/BrainRNASeqData'
        BrainAtlasResponse:
            type: object
            properties:
                geneName:
                    type: string
                atlasData:
                    type: object
        IDGResponse:
            type: object
            properties:
                geneName:
                    type: string
                idgData:
                    type: object
