# SPDX-FileCopyrightText: 2024 Cognitive Disorders Research Lab
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

# Accepted licesnes by default
accepted = ["Apache-2.0", "MIT"]
targets = [
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "i686-unknown-linux-gnu",
    "i686-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl"
]

# Do not ignore any dependencies
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false

# Try to resolve any time clearlydefined.io marks something as NOASSERTION
filter-noassertion = true
