---
title: "Untitled"
author: "Khaled Alganem"
date: "5/29/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)
knitr::opts_chunk$set(echo = F)

convert_na <- function(x, value = 1) {
  
  x <- ifelse(is.na(x), value, x)
  
  round(x,  4)
}

rating_column <- function(...) {
  colDef(align = "center", class = "cell number", ...)
}

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

rating_color <- make_color_pal(c("#e8e8e8","#969696","#050505"), bias = 1.3)

string_output <- readRDS("string_output.RDS")

string_test_table <- string_output$table %>% 
  mutate_if(is.numeric, convert_na)



```

## R Markdown


```{r cars}
reactable(string_test_table %>% select(-Description), 
          searchable = TRUE,
          striped = TRUE,
          bordered = TRUE,
          defaultColDef = colDef(
            align = "center",
            headerStyle = list(fontSize = '10px', align = "center"),
            cell = function(value) {
                color <- rating_color(value)
                value <- ""
                div(class = "spi-rating", style = list(background = color), value)
              }
            ),
          
          columns = list(
            Protein = colDef(
              cell = function(value) {
                value = value
              }
            )
            
          ), 
          
          details = function(index) {
                       paste(string_test_table$Description[[index]])
                     }
          )
```

## Including Plots

You can also embed plots, for example:

```{css}
.spi-rating {
  width: 20px;
  height: 20px;
  border: 1px solid rgba(0, 0, 0, 0.03);
  margin-left: auto;
  margin-right: auto;
  border-radius: 50%;
  color: #000;
  font-size: 13px;
  letter-spacing: -2px;
}
```


